# Generated by Django 5.0.14 on 2026-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='camera_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='lenses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='team_members_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
